import type { SkillPackDefinition } from '../intelligence-types.js'

export const BUILT_IN_SKILL_PACKS: SkillPackDefinition[] = [
  {
    id: 'technical-momentum',
    name: 'Technical Momentum',
    slug: 'technical-momentum',
    description: 'Uses technical analysis, trend strength, and support/resistance for directional setups.',
    category: 'analysis',
    toolNames: ['get_price'],
    committeeRoles: ['technical_analyst', 'portfolio_manager'],
    defaultConfig: { preferredMarkets: ['BTC/USD', 'ETH/USD', 'SOL/USD'] },
  },
  {
    id: 'sentiment-reader',
    name: 'Sentiment Reader',
    slug: 'sentiment-reader',
    description: 'Uses social and market sentiment to confirm or fade directional bias.',
    category: 'social',
    toolNames: ['get_sentiment'],
    committeeRoles: ['sentiment_analyst'],
    defaultConfig: { timeframe: '4h' },
  },
  {
    id: 'risk-guard',
    name: 'Risk Guard',
    slug: 'risk-guard',
    description: 'Applies deterministic risk rules before execution.',
    category: 'risk',
    toolNames: [],
    committeeRoles: ['risk_analyst'],
    defaultConfig: { strict: true },
  },
  {
    id: 'copy-trading-scout',
    name: 'Copy Trading Scout',
    slug: 'copy-trading-scout',
    description: 'Evaluates copy-trading suitability using scorecard and consistency signals.',
    category: 'copy_trading',
    toolNames: [],
    committeeRoles: ['portfolio_manager'],
    defaultConfig: { minTrivoScore: 60 },
  },
  {
    id: 'market-regime-adapter',
    name: 'Market Regime Adapter',
    slug: 'market-regime-adapter',
    description: 'Adapts trade size and confidence requirements to trending, volatile, and low-liquidity regimes.',
    category: 'analysis',
    toolNames: [],
    committeeRoles: ['technical_analyst', 'risk_analyst'],
    defaultConfig: { reduceSizeInVolatileRegime: true },
  },
]
